In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import QuantileTransformer

In [2]:
df = pd.read_csv('./data/titanic_clean.csv')
df.sample(5)

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
44          1       3  female  19.0      0      0   7.8792        Q
855         1       3  female  18.0      0      1   9.3500        S
62          0       1    male  45.0      1      0  83.4750        S
471         0       3    male  38.0      0      0   8.6625        S
21          1       2    male  34.0      0      0  13.0000        S

In [3]:
label_sex = LabelEncoder()
label_embarked = LabelEncoder()

df['Sex'] = label_sex.fit_transform(df['Sex'])
df['Embarked'] = label_embarked.fit_transform(df['Embarked'])

df.sample(5)

     Survived  Pclass  Sex        Age  SibSp  Parch    Fare  Embarked
45          0       3    1  29.699118      0      0   8.050         2
2           1       3    0  26.000000      0      0   7.925         2
669         1       1    0  29.699118      1      0  52.000         2
447         1       1    1  34.000000      0      0  26.550         2
115         0       3    1  21.000000      0      0   7.925         2

In [4]:
qun_tra_age = QuantileTransformer(output_distribution='normal', n_quantiles=500)
qun_tra_fare = QuantileTransformer(output_distribution='normal', n_quantiles=500)

df['Age'] = qun_tra_age.fit_transform(df[['Age']])
df['Fare'] = qun_tra_fare.fit_transform(df[['Fare']])

In [5]:
mms_pclass= MinMaxScaler()
mms_sex = MinMaxScaler()
mms_age = MinMaxScaler()
mms_sibsp = MinMaxScaler()
mms_parch = MinMaxScaler()
mms_fare = MinMaxScaler()
mms_embarked = MinMaxScaler()

df['Pclass'] = mms_pclass.fit_transform(df[['Pclass']])
df['Sex'] = mms_sex.fit_transform(df[['Sex']])
df['Age'] = mms_age.fit_transform(df[['Age']])
df['SibSp'] = mms_sibsp.fit_transform(df[['SibSp']])
df['Parch'] = mms_parch.fit_transform(df[['Parch']])
df['Fare'] = mms_fare.fit_transform(df[['Fare']])
df['Embarked'] = mms_embarked.fit_transform(df[['Embarked']])

df.sample(5)

     Survived  Pclass  Sex       Age  SibSp     Parch      Fare  Embarked
351         0     0.0  1.0  0.507253  0.000  0.000000  0.573454       1.0
367         1     1.0  0.0  0.507253  0.000  0.000000  0.357459       0.0
763         1     0.0  0.0  0.570590  0.125  0.333333  0.663973       1.0
823         1     1.0  0.0  0.467510  0.000  0.166667  0.482514       1.0
858         1     1.0  0.0  0.447788  0.000  0.500000  0.517241       0.0

In [6]:
df.to_csv('./data/titanic_procesado.csv', index=False)